# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/6.x/configuration.html
scheb_two_factor:
    security_tokens:
        # - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
    # config/routes/scheb_2fa.yaml
    email:
        enabled: true
        mailer: app.sendAuthCode
        sender_email: gti@geomadagascar.com
        sender_name: ConsoMyZone  # Optional
        digits: 6
        template: authenticator/2fa_form.html.twig
    trusted_device:
        enabled: true  
        manager: app.TrustedDeviceManagerCustom  # If the trusted device feature should be enabled
        # lifetime: 5184000              # Lifetime of the trusted device token
        # extend_lifetime: false         # Automatically extend lifetime of the trusted cookie on re-login
        # cookie_name: trusted_device    # Name of the trusted device cookie
        # cookie_secure: false           # true|false|auto Set the 'Secure' (HTTPS Only) flag on the trusted device cookie
        # cookie_same_site: "lax"        # The same-site option of the cookie, can be "lax", "strict" or null
        # cookie_path: "/"