<?php
namespace App\Form;

use App\Entity\FermeGeom;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\ChoiceList\ChoiceList;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AddEtabFermeType extends AbstractType{

    private $c=[
                ""=>"",
                "01" => "Ain",
                "02" => "Aisn",
                "03" => "Allier",
                "04" => "Alpes de Haute-Provence",
                "05" => "Hautes-Alpes",
                "06" => "Alpes-Maritimes",
                "07" => "Ardêche",
                "08" => "Ardennes",
                "09" => "Ariège",
                "10" => "Aube",
                "11" => "Aude",
                "12" => "Aveyron",
                "13" => "Bouches-du-Rhône",
                "14" => "Calvados",
                "15" => "Cantal",
                "16" => "Charente",
                "17" => "Charente-Maritime",
                "18" => "Cher",
                "19" => "Corrèze",
                "2A" => "Corse-du-Sud",
                "2B" => "Haute-Corse",
                "21" => "Côte-d'Or",
                "22" => "Côtes d'Armor",
                "23" => "Creuse",
                "24" => "Dordogne",
                "25" => "Doubs",
                "26" => "Drôme",
                "27" => "Eure",
                "28" => "Eure-et-Loir",
                "29" => "Finistère",
                "30" => "Gard",
                "31" => "Haute-Garonne",
                "32" => "Gers",
                "33" => "Gironde",
                "34" => "Hérault",
                "35" => "Île-et-Vilaine",
                "36" => "Indre",
                "37" => "Indre-et-Loire",
                "38" => "Isère",
                "39" => "Jura",
                "40" => "Landes",
                "41" => "Loir-et-Cher",
                "42" => "Loire",
                "43" => "Haute-Loire",
                "44" => "Loire-Atlantique",
                "45" => "Loiret",
                "46" => "Lot",
                "47" => "Lot-et-Garonne",
                "48" => "Lozère",
                "49" => "Maine-et-Loire",
                "50" => "Manche",
                "51" => "Marne",
                "52" => "Haute-Marne",
                "53" => "Mayenne",
                "54" => "Meurthe-et-Moselle",
                "55" => "Meuse",
                "56" => "Morbihan",
                "57" => "Moselle",
                "58" => "Nièvre",
                "59" => "Nord",
                "60" => "Oise",
                "61" => "Orne",
                "62" => "Pas-de-Calais",
                "63" => "Puy-de-Dôme",
                "64" => "Pyrénées-Atlantiques",
                "65" => "Hautes-Pyrénées",
                "66" => "Pyrénées-Orientales",
                "67" => "Bas-Rhin",
                "68" => "Haut-Rhin",
                "69" => "Rhône",
                "70" => "Haute-Saône",
                "71" => "Saône-et-Loire",
                "72" => "Sarthe",
                "73" => "Savoie",
                "74" => "Haute-Savoie",
                "75" => "Paris",
                "76" => "Seine-Maritime",
                "77" => "Seine-et-Marne",
                "78" => "Yvelines",
                "79" => "Deux-Sèvres",
                "80" => "Somme",
                "81" => "Tarn",
                "82" => "Tarn-et-Garonne",
                "83" => "Var",
                "84" => "Vaucluse",
                "85" => "Vendée",
                "86" => "Vienne",
                "87" => "Haute-Vienne",
                "88" => "Vosges",
                "89" => "Yonne",
                "90" => "Territoire-de-Belfort",
                "91" => "Essonne",
                "92" => "Hauts-de-Seine",
                "93" => "Seine-Saint-Denis",
                "94" => "Val-de-Marne",
                "95" => "Val-d'Oise"
    ];
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_ferme', TextType::class)
            ->add('adresse_ferme', TextType::class)
            ->add('code_postal', TextType::class)
            ->add('departement', ChoiceType::class, [
                'choices' =>[
                "01" => "01",
                "02" => "02",
                "03" => "03",
                "04" => "04",
                "05" => "05",
                "06" => "06",
                "07" => "07",
                "08" => "08",
                "09" => "09",
                "10" => "10",
                "11" => "11",
                "12" => "12",
                "13" => "13",
                "14" => "14",
                "15" => "15",
                "16" => "16",
                "17" => "17",
                "18" => "18",
                "19" => "19",
                "2A" => "2A",
                "2B" => "2B",
                "21" => "21",
                "22" => "22",
                "23" => "23",
                "24" => "24",
                "25" => "25",
                "26" => "26",
                "27" => "27",
                "28" => "28",
                "29" => "29",
                "30" => "30",
                "31" => "31",
                "32" => "32",
                "33" => "33",
                "34" => "34",
                "35" => "35",
                "36" => "36",
                "37" => "37",
                "38" => "38",
                "39" => "39",
                "40" => "40",
                "41" => "41",
                "42" => "42",
                "43" => "43",
                "44" => "44",
                "45" => "45",
                "46" => "46",
                "47" => "47",
                "48" => "48",
                "49" => "49",
                "50" => "50",
                "51" => "51",
                "52" => "52",
                "53" => "53",
                "54" => "54",
                "55" => "55",
                "56" => "56",
                "57" => "57",
                "58" => "58",
                "59" => "59",
                "60" => "60",
                "61" => "61",
                "62" => "62",
                "63" => "63",
                "64" => "64",
                "65" => "65",
                "66" => "66",
                "67" => "67",
                "68" => "68",
                "69" => "69",
                "70" => "70",
                "71" => "71",
                "72" => "72",
                "73" => "73",
                "74" => "74",
                "75" => "75",
                "76" => "76",
                "77" => "77",
                "78" => "78",
                "79" => "79",
                "80" => "80",
                "81" => "81",
                "82" => "82",
                "83" => "83",
                "84" => "84",
                "85" => "85",
                "86" => "86",
                "87" => "87",
                "88" => "88",
                "89" => "89",
                "90" => "90",
                "91" => "91",
                "92" => "92",
                "93" => "93",
                "94" => "94",
                "95" => "95",
                ],
                'choice_attr' => [
                    "01"=>['data-name'=>'Ain'],
                "02"=>['data-name'=>'Aisne'],
                "03"=>['data-name'=>'Allier'],
                "04"=>['data-name'=>'Alpes de Haute-Provence'],
                "05"=>['data-name'=>'Hautes-Alpes'],
                "06"=>['data-name'=>'Alpes-Maritimes'],
                "07"=>['data-name'=>'Ardêche'],
                "08"=>['data-name'=>'Ardennes'],
                "09"=>['data-name'=>'Ariège'],
                "10"=>['data-name'=>'Aube'],
                "11"=>['data-name'=>'Aude'],
                "12"=>['data-name'=>'Aveyron'],
                "13"=>['data-name'=>'Bouches-du-Rhône'],
                "14"=>['data-name'=>'Calvados'],
                "15"=>['data-name'=>'Cantal'],
                "16"=>['data-name'=>'Charente'],
                "17"=>['data-name'=>'Charente-Maritime'],
                "18"=>['data-name'=>'Cher'],
                "19"=>['data-name'=>'Corrèze'],
                "2A"=>['data-name'=>'Corse-du-Sud'],
                "2B"=>['data-name'=>'Haute-Corse'],
                "21"=>['data-name'=>'Côte-d\'Or'],
                "22"=>['data-name'=>'Côtes d\'Armor'],
                "23"=>['data-name'=>'Creuse'],
                "24"=>['data-name'=>'Dordogne'],
                "25"=>['data-name'=>'Doubs'],
                "26"=>['data-name'=>'Drôme'],
                "27"=>['data-name'=>'Eure'],
                "28"=>['data-name'=>'Eure-et-Loir'],
                "29"=>['data-name'=>'Finistère'],
                "30"=>['data-name'=>'Gard'],
                "31"=>['data-name'=>'Haute-Garonne'],
                "32"=>['data-name'=>'Gers'],
                "33"=>['data-name'=>'Gironde'],
                "34"=>['data-name'=>'Hérault'],
                "35"=>['data-name'=>'Île-et-Vilaine'],
                "36"=>['data-name'=>'Indre'],
                "37"=>['data-name'=>'Indre-et-Loire'],
                "38"=>['data-name'=>'Isère'],
                "39"=>['data-name'=>'Jura'],
                "40"=>['data-name'=>'Landes'],
                "41"=>['data-name'=>'Loir-et-Cher'],
                "42"=>['data-name'=>'Loire'],
                "43"=>['data-name'=>'Haute-Loire'],
                "44"=>['data-name'=>'Loire-Atlantique'],
                "45"=>['data-name'=>'Loiret'],
                "46"=>['data-name'=>'Lot'],
                "47"=>['data-name'=>'Lot-et-Garonne'],
                "48"=>['data-name'=>'Lozère'],
                "49"=>['data-name'=>'Maine-et-Loire'],
                "50"=>['data-name'=>'Manche'],
                "51"=>['data-name'=>'Marne'],
                "52"=>['data-name'=>'Haute-Marne'],
                "53"=>['data-name'=>'Mayenne'],
                "54"=>['data-name'=>'Meurthe-et-Moselle'],
                "55"=>['data-name'=>'Meuse'],
                "56"=>['data-name'=>'Morbihan'],
                "57"=>['data-name'=>'Moselle'],
                "58"=>['data-name'=>'Nièvre'],
                "59"=>['data-name'=>'Nord'],
                "60"=>['data-name'=>'Oise'],
                "61"=>['data-name'=>'Orne'],
                "62"=>['data-name'=>'Pas-de-Calais'],
                "63"=>['data-name'=>'Puy-de-Dôme'],
                "64"=>['data-name'=>'Pyrénées-Atlantiques'],
                "65"=>['data-name'=>'Hautes-Pyrénées'],
                "66"=>['data-name'=>'Pyrénées-Orientales'],
                "67"=>['data-name'=>'Bas-Rhin'],
                "68"=>['data-name'=>'Haut-Rhin'],
                "69"=>['data-name'=>'Rhône'],
                "70"=>['data-name'=>'Haute-Saône'],
                "71"=>['data-name'=>'Saône-et-Loire'],
                "72"=>['data-name'=>'Sarthe'],
                "73"=>['data-name'=>'Savoie'],
                "74"=>['data-name'=>'Haute-Savoie'],
                "75"=>['data-name'=>'Paris'],
                "76"=>['data-name'=>'Seine-Maritime'],
                "77"=>['data-name'=>'Seine-et-Marne'],
                "78"=>['data-name'=>'Yvelines'],
                "79"=>['data-name'=>'Deux-Sèvres'],
                "80"=>['data-name'=>'Somme'],
                "81"=>['data-name'=>'Tarn'],
                "82"=>['data-name'=>'Tarn-et-Garonne'],
                "83"=>['data-name'=>'Var'],
                "84"=>['data-name'=>'Vaucluse'],
                "85"=>['data-name'=>'Vendée'],
                "86"=>['data-name'=>'Vienne'],
                "87"=>['data-name'=>'Haute-Vienne'],
                "88"=>['data-name'=>'Vosges'],
                "89"=>['data-name'=>'Yonne'],
                "90"=>['data-name'=>'Territoire-de-Belfort'],
                "91"=>['data-name'=>'Essonne'],
                "92"=>['data-name'=>'Hauts-de-Seine'],
                "93"=>['data-name'=>'Seine-Saint-Denis'],
                "94"=>['data-name'=>'Val-de-Marne'],
                "95"=>['data-name'=>'Val-d\'Oise']
                ],
                'required' => true
                
            ])
            ->add('departement_name', TextType::class)
            ->add('email', TextType::class)
            ->add('fax', TextType::class)
            ->add('produit_ferme', TextType::class)
            ->add('telephone_domicile' , TelType::class)
            ->add('telephone_mobile', TelType::class)
            ->add('telephone_travail', TelType::class)
            ->add('ville', TextType::class);
            
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => FermeGeom::class,
        ]);
    }
}